services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "bughouse123"
      MYSQL_DATABASE: ${MYSQL_DATABASE:-BugHouse}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./server/.env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      # DB_USER/DB_PASS/DB_NAME read from server/.env
    ports:
      - "8000:8000"
    volumes:
      - ./server:/usr/src/server
      - .:/app

  client:
    build:
      context: ./client
    restart: unless-stopped
    env_file:
      - ./client/.env
    ports:
      - "3000:80" # host:container (serve React on host:3000)
    depends_on:
      - server

volumes:
  db_data: