-- MySQL Script generated by MySQL Workbench
-- Tue Jul 29 20:36:27 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BugHouse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BugHouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BugHouse` DEFAULT CHARACTER SET utf8 ;
USE `BugHouse` ;
USE `BugHouse` ;

-- -----------------------------------------------------
-- View `BugHouse`.`student_session_count`
-- -----------------------------------------------------
USE `BugHouse`;
CREATE  OR REPLACE VIEW `student_session_count` AS
SELECT
	s.studentID,
    s.studentName,
    COUNT(ts.sessionID) AS session_count
FROM
	Student s
LEFT JOIN
	Tutor_Session ts ON s.studentID = ts.Student_studentID
GROUP BY
	s.studentID,s.studentName;

-- -----------------------------------------------------
-- View `BugHouse`.`tutor_session_count`
-- -----------------------------------------------------
USE `BugHouse`;
CREATE  OR REPLACE VIEW `tutor_session_count` AS
SELECT
	t.tutorID,
    t.tutorName,
    COUNT(ts.sessionID) AS session_count
FROM
	Tutor t
LEFT JOIN
	Tutor_Session ts ON t.tutorID = ts.Tutor_tutorID
GROUP BY
	t.tutorID,t.tutorName;

-- -----------------------------------------------------
-- View `BugHouse`.`tutor_average_ratings`
-- -----------------------------------------------------
USE `BugHouse`;
CREATE  OR REPLACE VIEW `tutor_average_ratings` AS
SELECT
	t.tutorID,
    t.tutorName,
    AVG(ts.sessionRating) AS session_avg_rating
FROM
	Tutor t
LEFT JOIN
	Tutor_Session ts ON t.tutorID = ts.Tutor_tutorID
GROUP BY
	t.tutorID,t.tutorName;

-- -----------------------------------------------------
-- View `BugHouse`.`view_schedule`
-- -----------------------------------------------------
USE `BugHouse`;
CREATE  OR REPLACE VIEW `view_schedule` AS
SELECT 
	s.studentName,
    t.tutorID,
    t.tutorName,
    ts.timeslotID,
    sched.scheduleID,
    sched.scheduleDate AS scheduleDate,
    subj.subjectID,
    subj.subjectName,
    sess.sessionID,
    sess.sessionSignInTime,
    sess.sessionSignOutTime
FROM 
    Tutor t
JOIN 
    Timeslot ts ON t.tutorID = ts.Tutor_tutorID
JOIN 
    Daily_Schedule sched ON ts.Daily_Schedule_scheduleID = sched.scheduleID
JOIN 
    Academic_Subject subj ON ts.Academic_Subject_subjectID = subj.subjectID
LEFT JOIN 
    Tutor_Session sess ON ts.timeslotID = sess.Timeslot_timeslotID
LEFT JOIN 
    Student s ON sess.Student_studentID = s.studentID;

-- -----------------------------------------------------
-- View `BugHouse`.`view_booked_sessions`
-- -----------------------------------------------------
USE `BugHouse`;
CREATE  OR REPLACE VIEW `view_booked_sessions` AS
SELECT 
    s.studentID,
    s.studentName,
    t.tutorID,
    t.tutorName,
	ts.timeslotID,
    sched.scheduleID,
    sched.scheduleDate AS scheduleDate,
    subj.subjectID,
    subj.subjectName,
    sess.sessionID,
    sess.sessionSignInTime,
    sess.sessionSignOutTime,
    sess.sessionFeedback,
    sess.sessionRating
FROM 
    Student s
LEFT JOIN 
    Tutor_Session sess ON s.studentID = sess.Student_studentID
LEFT JOIN 
    Timeslot ts ON sess.Timeslot_timeslotID = ts.timeslotID
LEFT JOIN 
    Tutor t ON ts.Tutor_tutorID = t.tutorID
LEFT JOIN 
    Daily_Schedule sched ON ts.Daily_Schedule_scheduleID = sched.scheduleID
LEFT JOIN 
    Academic_Subject subj ON ts.Academic_Subject_subjectID = subj.subjectID;

-- -----------------------------------------------------
-- View `BugHouse`.`tutor_view_availability`
-- -----------------------------------------------------
USE `BugHouse`;
CREATE  OR REPLACE VIEW `tutor_view_availability` AS
SELECT
	t.tutorID,
    t.tutorName,
    ta.dayOfWeek,
    ta.startTime,
    ta.endTime
FROM
	Tutor t
JOIN
	Tutor_Availability ta ON ta.Tutor_tutorID = t.tutorID;

-- -----------------------------------------------------
-- View `BugHouse`.`view_available_timeslots`
-- -----------------------------------------------------
USE `BugHouse`;
CREATE  OR REPLACE VIEW `view_available_timeslots` AS
SELECT 
	s.studentName,
    t.tutorID,
    t.tutorName,
    ts.timeslotID,
    sched.scheduleID,
    sched.scheduleDate AS scheduleDate,
    subj.subjectID,
    subj.subjectName,
    sess.sessionID,
    sess.sessionSignInTime,
    sess.sessionSignOutTime
FROM 
    Tutor t
JOIN 
    Timeslot ts ON t.tutorID = ts.Tutor_tutorID
JOIN 
    Daily_Schedule sched ON ts.Daily_Schedule_scheduleID = sched.scheduleID
JOIN 
    Academic_Subject subj ON ts.Academic_Subject_subjectID = subj.subjectID
LEFT JOIN 
    Tutor_Session sess ON ts.timeslotID = sess.Timeslot_timeslotID
LEFT JOIN 
    Student s ON sess.Student_studentID = s.studentID
WHERE
	sess.sessionID IS NULL;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

